name: scroll_date_picker
description: A customizable and easy-to-use date picker library for Flutter. Compatible with Android & iOS & Web.
version: 3.4.0
homepage: https://github.com/mincheol-shin/scroll_date_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  clickable_list_wheel_view: ^0.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
